Adri
lucaswerner90/upc_dl_project_2021 pull request #4
Opened 2021-05-18 16:26 UTC by amolero6

2nd try having rebased with master branch... 
Class for dataset treatment that includes building vocabulary based on word frequency from input (pending to use torchtext and spacy).
Dataloader successfully loads each input (image converted to tensor through PIL) and target (caption converted to vector with vocabulary)

2021-05-18 16:48 UTC, lucaswerner90 requested changes
Minor comments that can be addressed later. Feel free to merge it

2021-05-18 16:48 UTC, lucaswerner90 commented on dataset.py
> +class Vocabulary():
put the class in a different file so is much clear to identify where it's. In general I would suggest a class per file

2021-05-18 16:48 UTC, lucaswerner90 commented on dataset.py
> +class CapsCollate:
same for this one. Maybe a module should be created in the project that contains the whole dataset classes structure

2021-05-18 16:48 UTC, lucaswerner90 commented on .gitignore
> +notes.txt
Even though you added it notes.txt here, it seems that it was added to the pull request anyway. Just deleted it from it

2021-05-19 15:25 UTC, amolero6 commented
Added a file per class and tested again

2021-05-19 16:56 UTC, lucaswerner90 approved these changes
looks fine

2021-05-20 08:05 UTC, merged